name: ijot
description: A simple note app.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.1.1+9

environment:
  sdk: ^3.7.0

dependencies:
  animated_search_bar: ^2.8.0
  another_flushbar: ^1.12.30
  app_version_update: ^6.1.3
  cloud_firestore: ^6.0.0
  cloud_firestore_web: ^5.0.0
  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.8
  equatable: ^2.0.7
  file_picker: ^10.3.2
  firebase_auth: ^6.0.1
  firebase_auth_web: ^6.0.1
  firebase_core: ^4.0.0
  firebase_crashlytics: ^5.0.0
  firebase_storage: ^13.0.0
  flutter:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_quill: ^11.4.2
  flutter_quill_extensions: ^11.0.0
  flutter_spinkit: ^5.2.2
  go_router: ^16.2.1
  google_sign_in: ^7.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.2.0
  intl: ^0.20.2
  modal_progress_hud_alt: ^1.0.0
  package_info_plus: ^8.3.1
  path: ^1.9.1
  path_provider: ^2.1.5
  path_url_strategy_module: ^1.0.2
  string_validator: ^1.2.0
  universal_html: ^2.2.4
  upgrader: ^11.5.0
  url_strategy: ^0.3.0
  uuid: ^4.5.1
  version: ^3.0.2
  youtube_player_flutter: ^9.1.2

dev_dependencies:
  build_runner: null
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  integration_test:
    sdk: flutter
  mocktail: ^1.0.4
  yaml: ^3.1.3
  yaml_edit: ^2.2.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launcher-icon.png"

# flutter_native_splash:
#   image: assets/images/splash.png
#   color: "410E61"
#   fill: true
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/translations/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: cabin
      fonts:
        - asset: assets/fonts/Cabin-Regular.ttf
        - asset: assets/fonts/Cabin-Bold.ttf
          weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
