// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbhqu9i5QYQv1dx-xE29vk72CNrfXmBBs',
    appId: '1:777445836697:web:2cb3976e59f342d7eaf508',
    messagingSenderId: '777445836697',
    projectId: 'ijot-1da7a',
    authDomain: 'ijot-1da7a.firebaseapp.com',
    databaseURL: 'https://ijot-1da7a.firebaseio.com',
    storageBucket: 'ijot-1da7a.appspot.com',
    measurementId: 'G-21K1WCERPQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArqSc7uTcVTLJOM5J-o5WAs8HhwnLQR2w',
    appId: '1:777445836697:android:db2554d8b125f91ceaf508',
    messagingSenderId: '777445836697',
    projectId: 'ijot-1da7a',
    databaseURL: 'https://ijot-1da7a.firebaseio.com',
    storageBucket: 'ijot-1da7a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtPSYH5Xcp4g-9soIT5N-G4a2fAD0DBXs',
    appId: '1:777445836697:ios:ba9dc98ce345f5ebeaf508',
    messagingSenderId: '777445836697',
    projectId: 'ijot-1da7a',
    databaseURL: 'https://ijot-1da7a.firebaseio.com',
    storageBucket: 'ijot-1da7a.appspot.com',
    androidClientId: '777445836697-103k8e3j2s2th2dv2kbuer28dht1qvi5.apps.googleusercontent.com',
    iosClientId: '777445836697-u2l83kqj1h6tccgovnmd3nskjqpidpus.apps.googleusercontent.com',
    iosBundleId: 'com.jabguru.iJot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtPSYH5Xcp4g-9soIT5N-G4a2fAD0DBXs',
    appId: '1:777445836697:ios:b333e228c3180900eaf508',
    messagingSenderId: '777445836697',
    projectId: 'ijot-1da7a',
    databaseURL: 'https://ijot-1da7a.firebaseio.com',
    storageBucket: 'ijot-1da7a.appspot.com',
    androidClientId: '777445836697-103k8e3j2s2th2dv2kbuer28dht1qvi5.apps.googleusercontent.com',
    iosClientId: '777445836697-tvgsrijm1dldet2j4omu5kmifv69h4o6.apps.googleusercontent.com',
    iosBundleId: 'com.jabguru.ijot',
  );
}
